### ISSUE TITLE
Box Error 

### ISSUE THREAD

**Issue by Lfted** [Hoodgail/readingplus#2]
![Help](https://user-images.githubusercontent.com/74383751/99002868-659acd80-24fa-11eb-8902-6ac99cd88669.PNG)
 The top Left only shows a box and not nothing else.  Also if untick the Check Log button and when i put it back it only shows the same Gray Box in the top left 
![Help2](https://user-images.githubusercontent.com/74383751/99003019-a5fa4b80-24fa-11eb-8ad7-ebb7f779cc45.PNG)
But in the main screen it shows the same thing. The only thing of what it works is when your looking for what book you want to read. It shows the stuff in the top left.
![Help3](https://user-images.githubusercontent.com/74383751/99003216-f1acf500-24fa-11eb-84de-6b2897c64ace.PNG)

**Comment by Hoodgail** [comment]
It dont show anything on the log cuz u didnt click anything

**Comment by zhiyan114** [comment]
you can close this issue now lol.
