### ISSUE TITLE
Yo server delete

### ISSUE THREAD

**Issue by zhiyan114** [Hoodgail/readingplus#3]
ay yo discord server got deleted. Did they delete your account too?

**Comment by Lfted** [comment]
noo they didn't. I notice that the discord server got deleted

**Comment by Lfted** [comment]
So what now ?

**Comment by zhiyan114** [comment]
Pretty sure his account did because he left the other answer server which he probably would never do. Plus the delete username would takes about 7 days before showing up so we'll have to wait until then to know or if he was able to get online again.

**Comment by zhiyan114** [comment]
I've updated my contact site with another discord server that affiliates with answer contribution so you can join through there.

**Comment by Lfted** [comment]
whats the discord name and link ?

**Comment by zhiyan114** [comment]
Go to https://rptrashtm.tk
Click on the button that gives you my contact and click join server.

**Comment by Hoodgail** [comment]
LOL, my acc for banned, they reported the server, add my new main ``Hoodgail#0001``

**Comment by zhiyan114** [comment]
yo luckass got #0001 tag
